config = struct();
grid = struct();
run = struct();
sv = struct();



model = mf.Model();
%model = mf.Model();
V2 = struct('typ', 'toroidal', ...
            'R', [30e-6, 30e-6]);

V1 = struct('typ', 'toroidal', ...
            'w', 2*pi*[123, 635], ...
            'c', struct('xy', [4e-6, 3e-6]), ...
            'W', 2*pi*1);

model.add_potential(V2);
model.add_potential(V1);

model.add_potential(struct('typ', 'vertical', ...
                           'width', 4e-6, ...
                            'U', struct('max', 4e-30)))

model.add_potential(struct('typ', 'ladder', ...
                           'n', 5, ...
                           'phi', pi*[1, 0.5, 0.6, 0.2, 3]));

model.add_potential(struct('typ', 'cosine', ...
                           'n', 2));


model.add_potential(struct('typ', 'cosine', ...
                           'n', 100, ...
                           'R', [6e-6, 8e-6]));