function [info] = getInfo(obj)
    info = ['General configurations:', newline,...
            '-----------------------', newline, ...
             'N = ', num2str(obj.config.N), newline, ...
             'T = ', num2str(obj.config.T), ' K', newline, ...
             newline];

    if ~isempty(obj.model.Vts)
        info = [info, 'Toroidal Potentials:', newline, ...
                      '--------------------', newline];
    end
    for i = 1:length(obj.model.Vts)
        Vt = obj.model.Vts(i);
        W = obj.config.hbar/(obj.config.M*Vt.R^2);
        info = [info, ...
                '(wr', num2str(i), ', wz', num2str(i), ')', ...
                ' = 2*pi*(', num2str(Vt.wr/(2*pi)), ...
                ', ', num2str(Vt.wz/(2*pi)), ') Hz', newline, ...
                'R', num2str(i), ' = ', num2str(Vt.R, '%.2g'), ' m', newline,...
                'Rotating quantum:', newline, ...
                'W', num2str(i), ' = 2*pi*', num2str(W/(2*pi), '%.2f'), ' Hz', newline, ...
                 newline];
    end
    
    if ~isempty(obj.model.Vts)
        info = [info, 'Vertical Potentials:', newline, ...
                      '--------------------', newline];
    end
    for i = 1:length(obj.model.Vbs)
        Vb = obj.model.Vbs(i);
        info = [info, ...
                'W', num2str(i), ' = 2*pi*', num2str(Vb.w/(2*pi)), ' Hz', newline, ...
                'U_max', num2str(i), ' = ', num2str(Vb.U_max, '%.2g'), ' J', newline, ...
                'a_max', num2str(i), ' = ', num2str(Vb.a_max, '%.2g'), ' m', newline, ...
                'Protocol: [', num2str(Vb.t_start, '%.2g'), ', ', ...
                               num2str(Vb.t_max_start, '%.2g'), ', ', ...
                               num2str(Vb.t_max_end, '%.2g'), ', ', ...
                               num2str(Vb.t_end, '%.2g'), ']', newline, ...
                 newline];
    end
    info = [info, 'System parameters:', newline, ...
                  '------------------', newline, ...
                  '(N, Nz) = (', num2str(obj.grid.N), ', ', ...
                                 num2str(obj.grid.Nz), ')', newline, ...
                  'folder = ', obj.Folder];
end


