function V = getV(obj, t)
V = 0;
U = obj.getU(t);
phi = obj.w*obj.config.to_time(t);

if obj.n > 0
    for i = 1 : obj.n
        V = V + U*exp(-(1/(2*obj.a_max^2))*...
                     (obj.grid.X.*sin(phi + obj.phi0(i))- ...
                      obj.grid.Y.*cos(phi + obj.phi0(i))).^2).*...
                    ((obj.grid.X.*cos(phi + obj.phi0(i)) + ...
                      obj.grid.Y.*sin(phi + obj.phi0(i)))>0).*...
                    ((obj.grid.X.^2 + ...
                      obj.grid.Y.^2) > obj.R_min.^2);    
    end
end

end